Document: synaptics-multimedia-pad
Title: Debian synaptics-multimedia-pad Manual
Author: <insert document author here>
Abstract: This manual describes what synaptics-multimedia-pad is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/synaptics-multimedia-pad/synaptics-multimedia-pad.sgml.gz

Format: postscript
Files: /usr/share/doc/synaptics-multimedia-pad/synaptics-multimedia-pad.ps.gz

Format: text
Files: /usr/share/doc/synaptics-multimedia-pad/synaptics-multimedia-pad.text.gz

Format: HTML
Index: /usr/share/doc/synaptics-multimedia-pad/html/index.html
Files: /usr/share/doc/synaptics-multimedia-pad/html/*.html

  
